### ISSUE TITLE
Think of new decorator ideas

### ISSUE THREAD

**Issue by MichalRedm** [Dawid64/decorify#8]

**Comment by Dawid64** [comment]
Few More ideas:
- [ ] Mode switch (to automatically pass arguments to all of function to distinguish between development, testing and usage)
- [ ] Authorization (require password or some key before running a function)
- [ ] cProfiler Logger (Uses cProfiler for measuring function performance and saves it in file / prints it with logger)
- [ ] Configuration assistance (the function default arguments are taken from configuration file (json, yaml etc))
- [ ] Partial profiling (profiling data gathered only about function, so only gathering informations about this function)
- [ ] Type checker with transformation (if possible type checker transforms the data)
